/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_DoSomething */

#ifndef _Included_my_DoSomething
#define _Included_my_DoSomething
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_DoSomething
 * Method:    sayHelloTo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_my_DoSomething_sayHelloTo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
